# Generated by Django 4.2.14 on 2024-07-26 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("house", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField(verbose_name="내용")),
                ("score", models.IntegerField(verbose_name="별점")),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="", verbose_name="이미지"),
                ),
                (
                    "region_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="house.region",
                        verbose_name="지역",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("finish", models.BooleanField(default=False)),
                ("content", models.TextField(verbose_name="내용")),
                ("title", models.CharField(max_length=50, verbose_name="제목")),
                (
                    "region_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="house.region",
                        verbose_name="지역",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="", verbose_name="이미지")),
                ("content", models.TextField(blank=True, verbose_name="내용")),
                (
                    "region_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="house.region",
                        verbose_name="지역",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
