# Generated by Django 4.2.14 on 2024-07-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0007_center_name"),
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Magazine",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="", verbose_name="이미지")),
                ("content", models.TextField(blank=True, verbose_name="내용")),
                (
                    "region_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="house.region",
                        verbose_name="지역",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
