# Generated by Django 4.2.14 on 2024-07-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_request_user_id_review_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
