# Generated by Django 4.2.14 on 2024-07-31 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_delete_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, upload_to="", verbose_name="이미지"),
        ),
        migrations.AlterField(
            model_name="magazine",
            name="image",
            field=models.ImageField(blank=True, upload_to="", verbose_name="이미지"),
        ),
    ]
