# Generated by Django 4.2.14 on 2024-08-03 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_alter_article_image_alter_magazine_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magazine",
            name="image",
            field=models.ImageField(blank=True, upload_to="", verbose_name="썸네일"),
        ),
        migrations.CreateModel(
            name="MagazinePhoto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="", verbose_name="글이미지"),
                ),
                (
                    "magazine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post.magazine",
                    ),
                ),
            ],
        ),
    ]
