# Generated by Django 4.2.14 on 2024-08-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_alter_magazine_image_magazinephoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magazinephoto",
            name="magazine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="post.magazine",
            ),
        ),
    ]
