# Generated by Django 4.2.14 on 2024-07-30 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house', '0011_centerreview_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='이미지')),
                ('finish', models.BooleanField(verbose_name='질문 해결 여부')),
                ('q_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='house.region', verbose_name='지역')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('a_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='답변자')),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.question', verbose_name='질문글')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
