# Generated by Django 4.2.14 on 2024-08-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_alter_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지'),
        ),
    ]
