# Generated by Django 4.2.14 on 2024-07-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PursueLifestyle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='추구하는 라이프스타일')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='lifestyle',
        ),
        migrations.AddField(
            model_name='user',
            name='pursue_lifestyle',
            field=models.ManyToManyField(to='accounts.pursuelifestyle'),
        ),
    ]
