# Generated by Django 4.2.14 on 2024-07-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=20, verbose_name='시'),
        ),
        migrations.AddField(
            model_name='user',
            name='goon',
            field=models.CharField(blank=True, max_length=20, verbose_name='군'),
        ),
        migrations.AddField(
            model_name='user',
            name='gu',
            field=models.CharField(blank=True, max_length=20, verbose_name='구'),
        ),
    ]
