# Generated by Django 4.2.14 on 2024-07-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pursuelifestyle_remove_user_lifestyle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pursue_lifestyle',
        ),
        migrations.AddField(
            model_name='user',
            name='pursue_lifestyle_id',
            field=models.ManyToManyField(blank=True, to='accounts.pursuelifestyle'),
        ),
    ]
