# Generated by Django 4.2.14 on 2024-07-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_city_user_goon_user_gu'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lifestyle',
            field=models.CharField(blank=True, max_length=30, verbose_name='라이프스타일'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=10, verbose_name='닉네임'),
        ),
    ]
