# Generated by Django 4.2.14 on 2024-07-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_like_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='goon',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gu',
        ),
        migrations.AddField(
            model_name='user',
            name='gugoon',
            field=models.CharField(blank=True, max_length=20, verbose_name='구 또는 군'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=20, verbose_name='시 또는 도'),
        ),
    ]
