# Generated by Django 4.2.14 on 2024-08-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_city_remove_user_gugoon_user_region_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=20, verbose_name='시 또는 도'),
        ),
        migrations.AddField(
            model_name='user',
            name='gugoon',
            field=models.CharField(blank=True, max_length=20, verbose_name='구 또는 군'),
        ),
    ]
