# Generated by Django 4.2.14 on 2024-08-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_city_user_gugoon"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profileimage",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="프로필사진"
            ),
        ),
    ]
