# Generated by Django 4.2.14 on 2024-08-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileimage_url',
            field=models.URLField(blank=True, null=True, verbose_name='프로필사진'),
        ),
    ]
