# Generated by Django 4.2.14 on 2024-07-25 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                ("location", models.CharField(max_length=100, verbose_name="위치")),
                ("photo", models.ImageField(upload_to="")),
                ("deposit", models.IntegerField()),
                ("price", models.IntegerField()),
                ("pyong", models.IntegerField()),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="House_type",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20, verbose_name="주거형태")),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Infra",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20, verbose_name="인프라")),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Mood",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20, verbose_name="분위기")),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("city", models.CharField(max_length=20, verbose_name="시")),
                ("gu", models.CharField(max_length=20, verbose_name="구")),
                ("dong", models.CharField(max_length=20, verbose_name="동")),
                ("htype_id", models.ManyToManyField(blank=True, to="house.house_type")),
                ("infra_id", models.ManyToManyField(blank=True, to="house.infra")),
                ("mood_id", models.ManyToManyField(blank=True, to="house.mood")),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="SilverTown_Service",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20, verbose_name="서비스명")),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="SilverTown",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                ("size", models.IntegerField()),
                ("location", models.CharField(max_length=100, verbose_name="위치")),
                (
                    "SilverTown_Service_id",
                    models.ManyToManyField(blank=True, to="house.house_type"),
                ),
                (
                    "region_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="house.region"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="House_Surroundings",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20, verbose_name="집 주변 정보")),
                ("distance", models.IntegerField()),
                (
                    "house_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="house.house"
                    ),
                ),
                (
                    "region_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="house.region"
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.AddField(
            model_name="house",
            name="region_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="house.region"
            ),
        ),
    ]
