# Generated by Django 4.2.14 on 2024-07-27 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="house", name="region_id",),
        migrations.RemoveField(model_name="house_surroundings", name="house_id",),
        migrations.RemoveField(model_name="house_surroundings", name="region_id",),
        migrations.RemoveField(model_name="silvertown", name="SilverTown_Service_id",),
        migrations.RemoveField(model_name="silvertown", name="region_id",),
        migrations.DeleteModel(name="SilverTown_Service",),
        migrations.DeleteModel(name="House",),
        migrations.DeleteModel(name="House_Surroundings",),
        migrations.DeleteModel(name="SilverTown",),
    ]
