# Generated by Django 4.2.14 on 2024-07-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0002_remove_house_region_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="region", name="dong",),
        migrations.AddField(
            model_name="region",
            name="goon",
            field=models.CharField(max_length=20, null=True, verbose_name="군"),
        ),
    ]
