# Generated by Django 4.2.14 on 2024-07-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0003_remove_region_dong_region_goon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="goon",
            field=models.CharField(
                blank=True, default="임의동", max_length=20, verbose_name="군"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="region",
            name="gu",
            field=models.CharField(blank=True, max_length=20, verbose_name="구"),
        ),
    ]
