# Generated by Django 4.2.14 on 2024-07-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0004_alter_region_goon_alter_region_gu"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hobby",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20, verbose_name="여가활동")),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Lifestyle",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20, verbose_name="라이프스타일")),
            ],
            options={"abstract": False,},
        ),
        migrations.RemoveField(model_name="region", name="htype_id",),
        migrations.RemoveField(model_name="region", name="mood_id",),
        migrations.DeleteModel(name="House_type",),
        migrations.DeleteModel(name="Mood",),
        migrations.AddField(
            model_name="region",
            name="hobby_id",
            field=models.ManyToManyField(blank=True, to="house.hobby"),
        ),
        migrations.AddField(
            model_name="region",
            name="lstyle_id",
            field=models.ManyToManyField(blank=True, to="house.lifestyle"),
        ),
    ]
