# Generated by Django 4.2.14 on 2024-07-27 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0005_hobby_lifestyle_remove_region_htype_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("address", models.TextField(verbose_name="상세주소")),
                (
                    "time",
                    models.CharField(blank=True, max_length=150, verbose_name="운영시간정보"),
                ),
                ("cost", models.IntegerField(verbose_name="이용비용")),
                (
                    "region_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="house.region",
                        verbose_name="지역",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="CenterReview",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(max_length=150, verbose_name="후기내용")),
                (
                    "center_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="house.center",
                        verbose_name="시설",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
