# Generated by Django 4.2.14 on 2024-07-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0006_center_centerreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="name",
            field=models.CharField(default="무명", max_length=20, verbose_name="센터명"),
            preserve_default=False,
        ),
    ]
