# Generated by Django 4.2.14 on 2024-07-28 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0007_center_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "center1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_center1",
                        to="house.center",
                    ),
                ),
                (
                    "center2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_center2",
                        to="house.center",
                    ),
                ),
                (
                    "center3",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_center3",
                        to="house.center",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
