# Generated by Django 4.2.14 on 2024-07-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0010_cart_center4_cart_center5_alter_cart_center1_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="region", name="goon",),
        migrations.RemoveField(model_name="region", name="gu",),
        migrations.AddField(
            model_name="region",
            name="gugoon",
            field=models.CharField(blank=True, max_length=20, verbose_name="구 또는 군"),
        ),
        migrations.AddField(
            model_name="region",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                default=0,
                max_digits=15,
                verbose_name="위도",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="region",
            name="longtitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                default="0",
                max_digits=15,
                verbose_name="겅도",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="region",
            name="city",
            field=models.CharField(max_length=20, verbose_name="시 또는 도 "),
        ),
    ]
