# Generated by Django 4.2.14 on 2024-07-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0011_remove_region_goon_remove_region_gu_region_gugoon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                default="0",
                max_digits=15,
                verbose_name="위도",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="center",
            name="longtitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                default="1",
                max_digits=15,
                verbose_name="겅도",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="center",
            name="cost",
            field=models.IntegerField(blank=True, verbose_name="이용비용"),
        ),
    ]
