# Generated by Django 4.2.14 on 2024-07-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0012_center_latitude_center_longtitude_alter_center_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="city_code",
            field=models.IntegerField(
                blank=True, default="0", verbose_name="프론트파일 도시코드"
            ),
            preserve_default=False,
        ),
    ]
