# Generated by Django 4.2.14 on 2024-07-31 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0011_centerreview_user_id"),
        ("house", "0013_region_city_code"),
    ]

    operations = []
