# Generated by Django 4.2.14 on 2024-07-31 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("house", "0014_merge_0011_centerreview_user_id_0013_region_city_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일시"),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("plan1", models.TextField(verbose_name="계획1")),
                ("plan2", models.TextField(verbose_name="계획2")),
                ("plan3", models.TextField(verbose_name="계획3")),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
