# Generated by Django 4.2.14 on 2024-08-02 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0015_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='region_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house.region', verbose_name='지역'),
        ),
    ]
