# Generated by Django 4.2.14 on 2024-08-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0016_report_region_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="centerreview",
            name="score",
            field=models.IntegerField(blank=True, null=True, verbose_name="별점"),
        ),
    ]
