# Generated by Django 4.2.14 on 2024-08-04 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0017_centerreview_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="center1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_center1",
                to="house.center",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="center2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_center2",
                to="house.center",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="center3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_center3",
                to="house.center",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="center4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_center4",
                to="house.center",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="center5",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_center5",
                to="house.center",
            ),
        ),
    ]
