# Generated by Django 4.2.14 on 2024-08-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0019_center_phonenum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="plan1",
            field=models.TextField(null=True, verbose_name="계획1"),
        ),
        migrations.AlterField(
            model_name="report",
            name="plan2",
            field=models.TextField(null=True, verbose_name="계획2"),
        ),
        migrations.AlterField(
            model_name="report",
            name="plan3",
            field=models.TextField(null=True, verbose_name="계획3"),
        ),
    ]
