# Generated by Django 4.2.14 on 2024-08-05 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("house", "0020_alter_report_plan1_alter_report_plan2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CenterPhoto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="", verbose_name="센터이미지"),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="house.center",
                    ),
                ),
            ],
        ),
    ]
