# Generated by Django 4.2.14 on 2024-08-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0020_alter_report_plan1_alter_report_plan2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerreview',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='썸네일'),
        ),
    ]
